#!/bin/bash

set -euo pipefail

dir=$(dirname "$(readlink -f "$0")")
tmp_dir=$(mktemp -d --suffix "-udevil")

# Create temporary directory.
mkdir -p "$tmp_dir"
pushd "$tmp_dir" > /dev/null

# Download udevil.
wget -O udevil.tar.gz https://github.com/IgnorantGuru/udevil/tarball/next
tar xzf udevil.tar.gz
mv IgnorantGuru-udevil-* "udevil-0.4.4+"
cd "udevil-0.4.4+"
ln -s distros/debian debian

# Patch udevil.
cp -t . "$dir/udevil/fix_exfat_nonempty.patch"
patch -p1 < fix_exfat_nonempty.patch
export DEBFULLNAME="Jakub Valenta"
export DEBEMAIL="jakub@jakubvalenta.cz"
dch -v 0.4.5-2 "Fix exfat support (remove default option nonempty)."

# Build udevil.
dpkg-buildpackage -us -uc -nc

# Move built udevil package to the directory where this script was called from.
mv -t "$dir/dist" ../udevil_*.deb

# Remove temporary directory.
popd > /dev/null
rm -r "$tmp_dir"
