#!/bin/bash

set -euo pipefail

if ! grep deb-src /etc/apt/sources.list; then
    cat <<EOF | sudo tee -a /etc/apt/sources.list
deb-src http://deb.debian.org/debian buster main
deb-src http://security.debian.org/debian-security buster/updates main
deb-src http://deb.debian.org/debian buster-updates main
EOF
else
    sudo sed /etc/apt/sources.list -i -e "s/#deb-src/deb-src/"
fi

version=0.4.4+

dir=$(dirname "$(readlink -f "$0")")
tmp_dir=$(mktemp -d --suffix "-udevil")
mkdir -p "$tmp_dir"
pushd "$tmp_dir" > /dev/null

set -x
sudo apt-get update
sudo apt-get build-dep -y udevil
wget -O udevil.tar.gz https://github.com/IgnorantGuru/udevil/tarball/next
tar xzf udevil.tar.gz
mv IgnorantGuru-udevil-* "udevil-$version"
cd "udevil-$version"
ln -s distros/debian debian
dpkg-buildpackage -us -uc -nc
mv -t "$dir/dist" ../udevil_*.deb

popd > /dev/null
rm -r "$tmp_dir"
